{{ $name := "mongodb" }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    name: {{ $name }}
    env: {{ .Values.environment }}
    role: database
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: {{ $name }}
        env: {{ .Values.environment }}
        role: database
    spec:
      containers:
        - image: mvertes/alpine-mongo
          name: {{ $name }}
          resources:
            requests:
              cpu: "100m"
              memory: "1024M"
            limits:
              cpu: "500m"
              memory: "2048M"
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
              name: {{ $name }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $name }}
spec:
  selector:
    name: {{ $name }}
    role: database
  type: ClusterIP
  ports:
    - name: {{ $name }}
      port: 27017
      protocol: TCP
      targetPort: {{ $name }}
