{{ $name := .Values.name }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    name: {{ $name }}
    env: {{ .Values.environment }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: {{ $name }}
        env: {{ .Values.environment }}
    spec:
      containers:
        - image: {{ .Values.registry }}
          name: {{ $name }}
          resources:
            requests:
              cpu: "200m"
              memory: "256M"
            limits:
              cpu: "500m"
              memory: "512M"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          env:
            - name: PORT
              value: "3000"
            - name: MONGODB_URL
              value: {{ .Values.mongodb_url }}
          ports:
            - containerPort: 3000
              name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: simpleapi.f8b8184f326740f9b169.eastus.aksapp.io
      http:
        paths:
          - backend:
              serviceName: {{ $name }}
              servicePort: {{ $name }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $name }}
spec:
  selector:
    name: {{ $name }}
    env: {{ .Values.environment }}
  type: LoadBalancer
  ports:
    - name: {{ $name }}
      port: 80
      targetPort: http
---
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: {{ $name }}
#   labels:
#     app: {{ $name }}
#     env: {{ .Values.environment }}
#     role: scaler
# spec:
#   scaleTargetRef:
#     kind: Deployment
#     name: {{ $name }}
#   minReplicas: 1
#   maxReplicas: 100
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50
#     - type: Resource
#       resource:
#         name: memory
#         target:
#           type: Utilization
#           averageUtilization: 70