apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: graphql-api
  labels:
    app: graphql-api
    env: production
    role: scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: graphql-api
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
