apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    name: mongodb
    env: production
    role: database
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mongodb
        env: production
        role: database
    spec:
      containers:
        - image: mvertes/alpine-mongo
          name: mongodb
          resources:
            requests:
              cpu: "100m"
              memory: "1024M"
            limits:
              cpu: "500m"
              memory: "2048M"
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 30
            successThreshold: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 60
            successThreshold: 5
            failureThreshold: 3
          ports:
            - containerPort: 27017
              name: mongodb
