kind: Service
apiVersion: v1
metadata:
  name: mongodb
spec:
  selector:
    name: mongodb
    role: database
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
