replicaCount: 1

namespace: stage
name: graphql
image:
  name: totvs_devs_graphql
  defaultRegistry: israelborba/

use:
  service: true

service:
  type: LoadBalancer
  ports:
    - name: port-80
      port: 80
      targetPort: 3000

container:
  env:
    - name: PORT
      value: "3000"
    - name: MONGODB_URL
      value: mongodb://10.12.4.129:27017
